/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import excecao.ServicoException;
import servico.CidadeServico;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author weth767
 */
public class TelaCarregamento extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public TelaCarregamento() {
        initComponents();
        /*seta o frame no meio da tela*/
        this.setLocationRelativeTo(null);
        /*seta a barra de progresso como 0*/
        progressBar.setValue(0);
        /*e a deixa invisível*/
        progressBar.setVisible(false);
        /*tenta fazer uma busca enquanto isso para realizar a instancia do entity manager*/
        final CidadeServico us = new CidadeServico();
        /*cria a thread*/
        Thread t = new Thread(){
            @Override
            /*no método run*/
            public void run() {
                /*deixa a barra visível*/
                progressBar.setVisible(true);
                /*com um laço, executa os valores da barra*/
                for(int i = 0; i <= 100; i++){
                    /*vai setando os valores na barra*/
                    progressBar.setValue(i);
                    try{
                        /*coloca um espera de 100 milisegundos*/
                        sleep(100);
                    }catch(InterruptedException ex){}
                }
                /*depois de executar, deixa a barra vísivel novamente*/
                progressBar.setVisible(false);
                /*abre a tela de login e fecha essa*/
                TelaCarregamento.getFrames()[0].setVisible(false);
                TelaLogin loginScreen = new TelaLogin();
                loginScreen.setVisible(true);
                TelaCarregamento.getFrames()[0].dispose();
            }

        };
        t.setPriority(2);
        t.start();
        Thread t2 = new Thread(){
            /*instancia o entity manager*/
            @Override
            public void run() {
                us.buscaTodos();
            }
        };
        t2.setPriority(2);
        t2.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ACEA");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        progressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarregamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
