/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.PessoaDao;
import modelo.Pessoa;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.event.KeyEvent;
import modelo.Medico;
import modelo.Secretaria;
import servico.MedicoServico;
import servico.SecretariaServico;

/**
 *
 * @author weth767
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form SystemLoginScreen
     */
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /*método para verificar se o login e a senha são válidos*/
    public boolean verificaLogin(String login, String senha){
        /*instancia a classe de serviço de todos os que podem logar*/
        PessoaDao pessoaDao = new PessoaDao();
        /*verifica alguns possíveis glitchs para tentar validar senhas não validas e também verifica se encontra
        * a senha e o login*/
        Medico m = new MedicoServico().buscaPorLoginSenha(login, senha);
        Secretaria s = new SecretariaServico().buscaPorLoginSenha(login, senha);
        System.out.println(m);
        System.out.println(s);
        if(senha.matches("\\d+=\\d+") || senha.toLowerCase().matches("true = true")
                || senha.toLowerCase().matches("false = false") || (m == null && s == null)){
            /*senão encontrar, mostra mensagem de erro*/
            JOptionPane.showMessageDialog(this,"Erro em realizar o login, login ou senha inválida");
        }
        /*se encontrar*/
        else{
            JOptionPane.showMessageDialog(this,"Usuário conectado com sucesso","Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            /*passa o usuário para a tela principal e instancia ela*/
            TelaPrincipal telaPrincipal = new TelaPrincipal(m,s);
            telaPrincipal.setVisible(true);
            /*finaliza a tela atual*/
            this.setVisible(false);
            this.dispose();
        }
        /*caso houve erro na execução dos métodos de busca de usuário*/
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        btnConnect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login do Sistema");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        labelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login-24.png"))); // NOI18N
        labelLogin.setText("Usuário");
        labelLogin.setToolTipText("");

        textLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textLoginKeyTyped(evt);
            }
        });

        labelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/password-24.png"))); // NOI18N
        labelPassword.setText("Senha");

        textPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPasswordKeyTyped(evt);
            }
        });

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/connect-24.png"))); // NOI18N
        btnConnect.setToolTipText("Conectar ao Sistema");
        btnConnect.setBorderPainted(false);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel-24.png"))); // NOI18N
        btnCancel.setToolTipText("Cancelar Operação");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnConnect)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogin)
                    .addComponent(labelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textLogin)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int answer = JOptionPane.showConfirmDialog(this,"Deseja realmente sair do sistema?",
                "Verificação de saída", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(answer == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int answer = JOptionPane.showConfirmDialog(this,"Deseja realmente sair do sistema?",
                "Verificação de saída", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(answer == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        String password = new String(textPassword.getPassword());
        verificaLogin(textLogin.getText(),password);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
       if(evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_TAB){
           textLogin.requestFocus();
       }
    }//GEN-LAST:event_formKeyTyped

    private void textLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLoginKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER  || evt.getKeyChar() == KeyEvent.VK_TAB){
            textLogin.requestFocus();
        }
    }//GEN-LAST:event_textLoginKeyTyped

    private void textPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPasswordKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            String password = new String(textPassword.getPassword());
            verificaLogin(textLogin.getText(),password);
        }
        if(evt.getKeyChar() == KeyEvent.VK_TAB){
            textLogin.requestFocus();
        }
    }//GEN-LAST:event_textPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConnect;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTextField textLogin;
    private javax.swing.JPasswordField textPassword;
    // End of variables declaration//GEN-END:variables
}
