/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.agendamento.TelaAgendamento;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import visao.convenio.TelaCadastroConvenio;
import visao.convenio.TelaConsultaConvenio;
import visao.paciente.TelaCadastroPaciente;
import visao.paciente.TelaConsultaPaciente;

/**
 *
 * @author weth767
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private JDesktopPane painel;
    
    
    public TelaPrincipal() {
        initComponents();
        Dimension DimMax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(DimMax);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        painel = new JDesktopPane();
        setContentPane(painel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuPaciente = new javax.swing.JMenu();
        menuItemCadastroPaciente = new javax.swing.JMenuItem();
        menuItemConsultaPaciente = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        menuItemAgendaConsulta = new javax.swing.JMenuItem();
        menuConvenio = new javax.swing.JMenu();
        menuItemCadastraConvenio = new javax.swing.JMenuItem();
        menuItemConsultaConvenio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software Gerente de Clínica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuPaciente.setText("Paciente");

        menuItemCadastroPaciente.setText("Cadastro de Paciente");
        menuItemCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroPacienteActionPerformed(evt);
            }
        });
        menuPaciente.add(menuItemCadastroPaciente);

        menuItemConsultaPaciente.setText("Consulta de Paciente");
        menuItemConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaPacienteActionPerformed(evt);
            }
        });
        menuPaciente.add(menuItemConsultaPaciente);

        jMenuBar1.add(menuPaciente);

        menuAgendamento.setText("Agendamento");

        menuItemAgendaConsulta.setText("Agendar Consulta/Procedimento");
        menuItemAgendaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgendaConsultaActionPerformed(evt);
            }
        });
        menuAgendamento.add(menuItemAgendaConsulta);

        jMenuBar1.add(menuAgendamento);

        menuConvenio.setText("Convênio");

        menuItemCadastraConvenio.setText("Cadastro de Convênio");
        menuItemCadastraConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastraConvenioActionPerformed(evt);
            }
        });
        menuConvenio.add(menuItemCadastraConvenio);

        menuItemConsultaConvenio.setText("Consulta de Convênio");
        menuItemConsultaConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaConvenioActionPerformed(evt);
            }
        });
        menuConvenio.add(menuItemConsultaConvenio);

        jMenuBar1.add(menuConvenio);

        jMenu2.setText("jMenu2");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAgendaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgendaConsultaActionPerformed
       TelaAgendamento telaAgendamento = new TelaAgendamento(this);
       telaAgendamento.setVisible(true);
       painel.add(telaAgendamento);
    }//GEN-LAST:event_menuItemAgendaConsultaActionPerformed

    private void menuItemCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroPacienteActionPerformed
        TelaCadastroPaciente tcp = new TelaCadastroPaciente();
        tcp.setVisible(true);
        painel.add(tcp);
    }//GEN-LAST:event_menuItemCadastroPacienteActionPerformed

    private void menuItemConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaPacienteActionPerformed
        TelaConsultaPaciente tcp = new TelaConsultaPaciente(this);
        tcp.setVisible(true);
        painel.add(tcp);
    }//GEN-LAST:event_menuItemConsultaPacienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema?");
        if(resposta == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void menuItemCadastraConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastraConvenioActionPerformed
        TelaCadastroConvenio tcc = new TelaCadastroConvenio();
        tcc.setVisible(true);
        painel.add(tcc);
    }//GEN-LAST:event_menuItemCadastraConvenioActionPerformed

    private void menuItemConsultaConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaConvenioActionPerformed
        TelaConsultaConvenio tcc = new TelaConsultaConvenio(this);
        tcc.setVisible(true);
        painel.add(tcc);
    }//GEN-LAST:event_menuItemConsultaConvenioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuConvenio;
    private javax.swing.JMenuItem menuItemAgendaConsulta;
    private javax.swing.JMenuItem menuItemCadastraConvenio;
    private javax.swing.JMenuItem menuItemCadastroPaciente;
    private javax.swing.JMenuItem menuItemConsultaConvenio;
    private javax.swing.JMenuItem menuItemConsultaPaciente;
    private javax.swing.JMenu menuPaciente;
    // End of variables declaration//GEN-END:variables
}
